theme: minima
title: Miguel Leon
author: mald32
email: mald32@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sitio de carga de archivos personales. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: mald32 # DO NOT include the @ character, or else the build will fail!
github_username:  mald32 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
